### ISSUE TITLE
Support for Linux and OSX

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-nuke#19]
It struck me the that this integration is probably only supported on Windows, due to [the use of `where()`](https://github.com/pyblish/pyblish-nuke/blob/4e1f36306ba4421f9134b6474de77d68ca593073/pyblish_nuke/lib.py#L68).

We need `where`, because Nuke has an executable called `python` in it's own directory, and where bypasses this by only considering those on the `PATH`.

How can we solve this for other platforms?

**Comment by darkvertex** [comment]
I was glancing at the issues in this repo and saw this. Latest master branch doesn't have `where()` so I think this issue is probably outdated and worth closing maybe?

**Comment by tokejepsen** [comment]
@darkvertex are you able to test on Linux?

**Comment by darkvertex** [comment]
I could.

What should I try? Just see if I can summon a UI from the Python script editor?

**Comment by tokejepsen** [comment]
Yeah, I think you just need to get either pyblish-lite or pyblish-lite up and running from the readme.

**Comment by darkvertex** [comment]
I confirm it works. :+1: 

![image](https://user-images.githubusercontent.com/941331/46027080-fc0d9a00-c0ba-11e8-9c8e-9eee277a7d4f.png)

I'm on `CentOS Linux release 7.4.1708 (Core)` with with **Nuke 10.5.6**, `pyblish-nuke-2.1.2`, `pyblish-base-1.6.1` and `pyblish-qml-1.7.4`.

(I imagine it works with newer versions too.)

**Comment by tokejepsen** [comment]
Awesome! Thanks @darkvertex.

I'll close this issue for now.
