### ISSUE TITLE
Qt5: AttributeError: 'module' object has no attribute 'QProgressBar'

### ISSUE THREAD

**Issue by monsteradurm** [pyblish/pyblish-nuke#39]
Hi I am getting the error

'module' object has no attribute 'QProgressBar'

```
import pyblish.api
import pyblish_qml.api as api
import pyblish_qml
os.environ["PYTHONPATH"] = os.sep.join(pyblish_qml.file.rsplit(os.sep)[:-2])
os.environ["QML2_IMPORT_PATH"] = 'C:/Python27/Lib/site-packages/PyQt5/qml'
pyblish.api.register_gui("pyblish_qml")
api.register_python_executable("C:/python27/python.exe")
api.register_pyqt5('C:/Python27/Lib/site-packages/PyQt5')
pyblish.api.register_gui("pyblish_qml")

# 2. Set-up Pyblish for Nuke
import pyblish_nuke
pyblish_nuke.setup()
```

**Comment by monsteradurm** [comment]
Hi I am getting the error

> 'module' object has no attribute 'QProgressBar'

        ```
import pyblish.api
        import pyblish_qml.api as api
        import pyblish_qml
        os.environ["PYTHONPATH"] = os.sep.join(pyblish_qml.__file__.rsplit(os.sep)[:-2])
        os.environ["QML2_IMPORT_PATH"] = 'C:/Python27/Lib/site-packages/PyQt5/qml'
        pyblish.api.register_gui("pyblish_qml")
        api.register_python_executable("C:/python27/python.exe")
        api.register_pyqt5('C:/Python27/Lib/site-packages/PyQt5')

        pyblish.api.register_gui("pyblish_qml")

        # 2. Set-up Pyblish for Nuke
        import pyblish_nuke
        pyblish_nuke.setup()
```

**Comment by tokejepsen** [comment]
Hey @monsteradurm,

Thank you for reporting this, and I'm sorry to hear you are encountering bugs.

I can't replicate this. I did however find a bug while testing this out which has been fixed now with  https://github.com/pyblish/pyblish-nuke/releases/tag/2.1.1.

Are you able to try the latest version?

**Comment by monsteradurm** [comment]
I upgraded to the latest version. This is the response I am getting now:

`Traceback (most recent call last):
  File "C:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Lib\site-packages\pyblish_qml\__main__.py", line 4, in <module>
    import argparse
  File "C:\python27\lib\argparse.py", line 86, in <module>
    import copy as _copy
  File "C:\python27\lib\copy.py", line 52, in <module>
    import weakref
  File "C:\python27\lib\weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref`

**Comment by tokejepsen** [comment]
Hey @monsteradurm,

Something seems very wrong with your Python installation. Could you try to reinstall Python?

**Comment by tokejepsen** [comment]
Hey @monsteradurm,

Did you get any further with this?

**Comment by mruegenberg** [comment]
I'm having a similar issue when using `pyblish_nuke.publish()`, using pyblish_nuke v.2.1.3

```
# Result: Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/media/pipeline/code/pipeline/lib/pythonlibs/lib/python3.7/site-packages/pyblish_nuke/lib.py", line 182, in publish
    splash = Splash()
  File "/media/pipeline/code/pipeline/lib/pythonlibs/lib/python3.7/site-packages/pyblish_nuke/lib.py", line 173, in __init__
    self.bar = QtGui.QProgressBar()
AttributeError: module 'Qt.QtGui' has no attribute 'QProgressBar'
```

It appears there's an incompatibility between Qt.py and the code in lib.py?
It calls `self.bar = QtGui.QProgressBar()`, but in Qt.py QProgressBar is listed within `QtWidgets`

Replacing QtGui with QtWidgets in the relevant line appears to fix the bug.

**Comment by mottosso** [comment]
Thanks for this, I've updated this now and made a new GitHub release, 2.1.4
