### ISSUE TITLE
Vendor Qt.py

### ISSUE THREAD

**Issue by mruegenberg** [pyblish/pyblish-nuke#45]
Hello, 
I seem to have a similar issue to this one described in [#pyblish-lite/103](https://github.com/pyblish/pyblish-lite/issues/103).

The solution described there (replacing `.vendor.Qt` by `Qt` so the install of Qt.py 1.3.8 from my local environment is used) also works for me with pyblish-nuke. (Note I'm also using pyblish-lite but didn't have to replace the vendor.Qt import there)

This is with Nuke 13.2v8.

**Comment by mruegenberg** [comment]
Okay, so the actual issue seems to be that v2.1.3 is not on pypi and thus when I just install it via `pip install`, v2.1.2 is used.
Would it be possible to add the latest release to pypi?

**Comment by mottosso** [comment]
Try this.

```bash
pip install git+https://github.com/pyblish/pyblish-nuke.git
```
