### ISSUE TITLE
Images missing in distribution

### ISSUE THREAD

**Issue by mruegenberg** [pyblish/pyblish-nuke#48]
When installing via pip the images (splash.png etc) seem to be missing...

I don't know much about Python package distribution, but would assume the fix would be to change, in `setup.py`:

```
package_data={"pyblish_nuke": ["plugins/*.py", "nuke_path/*.py"]},
```
to
```
package_data={"pyblish_nuke": ["plugins/*.py", "nuke_path/*.py", "*.png"]},
```

**Comment by mottosso** [comment]
That looks right, here's how Pyblish Lite does it.

https://github.com/pyblish/pyblish-lite/blob/1692cb5e537d5a0c63ddf76ff885ccf20728166e/setup.py#L37-L44

I've pushed an update with this now, give it a try.
